# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='linear')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss='mse', optimizer='adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 738ms/step - loss: 559.7816
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 559.2161
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 558.6509
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 558.0861
Epoch 5/10
1/1 [==============================] - 0s 14ms/step - loss: 557.5214
Epoch 6/10
1/1 [==============================] - 0s 17ms/step - loss: 556.9572
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 556.3932
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 555.8296
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 555.2662
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 554.7032


In [ ]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 124ms/step
[ 0.00999822 -0.18541542 -0.38082904 -0.5762427  -0.77165633 -0.96707
 -1.1624836  -1.3578973  -1.5533109  -1.7487245  -1.9441382  -2.1395516
 -2.3349652  -2.5303788  -2.7257926  -2.9212062  -3.1166198  -3.3120334
 -3.507447   -3.7028608 ]


## Now, Your turn!

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [ ]:
x.shape, y.shape

((20,), (20,))

In [ ]:
# 기존의 것 클리어
keras.backend.clear_session()
# 레이어들을 사슬로 연결하 듯 연결
input_layer = keras.layers.Input(shape=(1,))
hl1 = keras.layers.Dense(256)(input_layer)
hl2 = keras.layers.Dense(256)(hl1)
output_layer = keras.layers.Dense(1)(hl2)
# 모델의 시작과 끝 연결
model = keras.models.Model(inputs = input_layer, outputs = output_layer)
# 컴파일해주렴
model.compile(loss='mse', optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=2)

Epoch 1/10
1/1 - 1s - loss: 676.3361 - 885ms/epoch - 885ms/step
Epoch 2/10
1/1 - 0s - loss: 455.8793 - 11ms/epoch - 11ms/step
Epoch 3/10
1/1 - 0s - loss: 281.9045 - 9ms/epoch - 9ms/step
Epoch 4/10
1/1 - 0s - loss: 154.1534 - 15ms/epoch - 15ms/step
Epoch 5/10
1/1 - 0s - loss: 71.9834 - 10ms/epoch - 10ms/step
Epoch 6/10
1/1 - 0s - loss: 33.0839 - 11ms/epoch - 11ms/step
Epoch 7/10
1/1 - 0s - loss: 31.5033 - 10ms/epoch - 10ms/step
Epoch 8/10
1/1 - 0s - loss: 55.5535 - 9ms/epoch - 9ms/step
Epoch 9/10
1/1 - 0s - loss: 88.4181 - 9ms/epoch - 9ms/step
Epoch 10/10
1/1 - 0s - loss: 114.5337 - 7ms/epoch - 7ms/step


In [ ]:
y_pred = model.predict(x)

1/1 [==============================] - 0s 114ms/step


In [ ]:
y_pred[:5]

array([[ -0.254225 ],
       [ -3.3539271],
       [ -6.4536295],
       [ -9.553331 ],
       [-12.653033 ]], dtype=float32)

In [ ]:
y[:5]

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

#모델 만들기
model = keras.models.Sequential()
# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 484ms/step - loss: 1.0394 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 1.0370 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 1.0346 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 1.0322 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: 1.0298 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 1.0274 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 1.0250 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 1.0226 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 1.0202 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 1.0178 - accuracy: 0.5500


In [ ]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
1/1 [==============================] - 0s 54ms/step
[0.4975006  0.5960972  0.6874998  0.76632655 0.830181   0.87933385
 0.9157044  0.9418375  0.96022075 0.97296053 0.981698   0.9876479
 0.9916799  0.99440324 0.9962385  0.99747354 0.9983038  0.99886143
 0.9992359  0.9994873 ]


## Now, Your turn!

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [ ]:
x.shape, y.shape

((40,), (40,))

In [ ]:
# 기존의 모델 날리기
keras.backend.clear_session()
# 레이어 발판 생성
model = keras.models.Sequential()
# 레이어 블록 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))
# 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [ ]:
a = model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 15ms/step - loss: 21.2950 - accuracy: 0.4750
Epoch 2/10
2/2 [==============================] - 0s 8ms/step - loss: 21.2634 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 7ms/step - loss: 21.2336 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 21.2044 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 6ms/step - loss: 21.1746 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 6ms/step - loss: 21.1450 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 11ms/step - loss: 21.1157 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 5ms/step - loss: 21.0854 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 7ms/step - loss: 21.0573 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 6ms/step - loss: 21.0264 - accuracy: 0.4750


In [ ]:
a.history

{'loss': [21.295024871826172,
  21.263378143310547,
  21.233556747436523,
  21.20441436767578,
  21.174596786499023,
  21.144996643066406,
  21.11570167541504,
  21.085378646850586,
  21.057313919067383,
  21.0263671875],
 'accuracy': [0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355]}

In [ ]:
y_pred = model.predict(x)

2/2 [==============================] - 0s 7ms/step


In [ ]:
y_pred[:5] # 확률 : 높을 수록 1에 가깝다 -> 01111 예측

array([[0.49500862],
       [0.5912211 ],
       [0.6809189 ],
       [0.7589588 ],
       [0.82287693]], dtype=float32)

In [ ]:
y[:5]

array([0, 0, 0, 0, 0])