# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20))
y = x * 2 - 1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 380ms/step - loss: 226.7736
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 226.4141
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 226.0548
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 225.6959
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 225.3372
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 224.9789
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 224.6208
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 224.2631
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 223.9058
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 223.5487


In [ ]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 52ms/step


array([9.9972216e-03, 5.8880281e-01, 1.1676084e+00, 1.7464139e+00,
       2.3252194e+00, 2.9040248e+00, 3.4828305e+00, 4.0616364e+00,
       4.6404419e+00, 5.2192473e+00, 5.7980528e+00, 6.3768587e+00,
       6.9556642e+00, 7.5344696e+00, 8.1132755e+00, 8.6920805e+00,
       9.2708864e+00, 9.8496923e+00, 1.0428497e+01, 1.1007303e+01],
      dtype=float32)

## Now, Your turn!

In [ ]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x))

## Now, Your turn!

In [ ]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)