# Keras로 Linear&Logistic Regression 조금 더 맛보기
---

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

##Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [ ]:
boston = load_boston()

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [7]:
y[:3]

array([24. , 21.6, 34.7])

In [5]:
import tensorflow as tf
from tensorflow import keras
import numpy as mp

In [14]:
keras.backend.clear_session
model = keras.models.Sequential()
model.add(keras.layers.Input(shape=(13,)))
model.add(keras.layers.Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='adam')

In [9]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 73413.6016
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 65800.9453
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 58904.9492
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 52452.0703
Epoch 5/10
16/16 [==============================] - 0s 3ms/step - loss: 46651.5898
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 41323.2930
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 36558.1641
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 32315.6934
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 28427.6855
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 24980.6777


In [11]:
print(y[:5])

[24.  21.6 34.7 33.4 36.2]


In [12]:
model.predict(x).reshape(-1)[:5]

16/16 [==============================] - 0s 2ms/step


array([107.65215,  93.60636,  86.71663,  73.73453,  76.86556],
      dtype=float32)

In [43]:
boston = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv')
x = boston.iloc[:,:-1]
y = boston.iloc[:,-1]
x.shape, y.shape

((506, 12), (506,))

In [44]:
keras.backend.clear_session
model = keras.models.Sequential()
model.add(keras.layers.Input(shape=(12,)))
model.add(keras.layers.Dense(1, activation='linear'))
model.compile(loss=keras.losses.mean_squared_error, optimizer=keras.optimizers.Adam())

In [45]:
model.fit(x, y, epochs=10, verbose=1)
model.predict(x).reshape(-1)[:5]

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 4725.7407
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 3624.8269
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 2740.8474
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 2062.9282
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 1548.8318
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 1169.2781
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 905.2879
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 717.4586
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 596.0543
Epoch 10/10
16/16 [==============================] - 0s 1ms/step


array([14.311057, 16.158155, 16.894062, 17.064285, 16.423475],
      dtype=float32)

In [46]:
y[:5]

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64

## Logistic Regression 쬐금 더 어려운 데이터

In [15]:
from sklearn.datasets import load_breast_cancer

In [16]:
cancer = load_breast_cancer()

In [21]:
x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

In [24]:
np.unique(y)

array([0, 1])

In [29]:
# 이전 모델 없애기
keras.backend.clear_session
# 모델 생성
model = keras.models.Sequential()
# 추가
model.add(keras.layers.Input(shape=(30,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))
# 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [30]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 1s 5ms/step - loss: 25.9889 - accuracy: 0.6046
Epoch 2/10
18/18 [==============================] - 0s 4ms/step - loss: 12.4522 - accuracy: 0.1968
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 10.2389 - accuracy: 0.1916
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 9.2324 - accuracy: 0.1230
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 8.4687 - accuracy: 0.1107
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 7.5537 - accuracy: 0.1142
Epoch 7/10
18/18 [==============================] - 0s 3ms/step - loss: 6.6604 - accuracy: 0.1072
Epoch 8/10
18/18 [==============================] - 0s 5ms/step - loss: 5.7327 - accuracy: 0.1248
Epoch 9/10
18/18 [==============================] - 0s 4ms/step - loss: 4.8991 - accuracy: 0.1283
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 4.0424 - accuracy: 0.1529


In [31]:
model.predict(x).reshape(-1)[:5] # 1 1 0 0 0

18/18 [==============================] - 0s 2ms/step


array([9.9978173e-01, 9.9947095e-01, 3.1809646e-01, 2.9612637e-01,
       4.6304660e-05], dtype=float32)

In [32]:
y[:5]

array([0, 0, 0, 0, 0])