In [ ]:
import pandas as pd
import numpy as np

In [ ]:
X_train = pd.read_csv('df_X_train.csv')
X_test = pd.read_csv('df_X_test.csv')

FileNotFoundError: ignored

In [ ]:
X_train

url_len  url_num_hyphens_dom  url_path_len  url_domain_len  \
0        23.0                  0.0           8.0            15.0   
1        75.0                  0.0          58.0            17.0   
2        20.0                  0.0           4.0            16.0   
3        27.0                  0.0          13.0            14.0   
4        39.0                  2.0          12.0            27.0   
...       ...                  ...           ...             ...   
3657     68.0                  3.0          16.0            52.0   
3658     66.0                  0.0          48.0            18.0   
3659     90.0                  1.0          64.0            26.0   
3660     46.0                  0.0          33.0            13.0   
3661     18.0                  0.0           0.0            18.0   

      url_hostname_len  url_num_dots  url_num_underscores  url_query_len  \
0                 15.0           2.0                  0.0            0.0   
1                 17.0           6.0                  0.0            0.0   
2                 16.0           2.0                  0.0            0.0   
3                 14.0           3.0                  0.0            0.0   
4                 27.0           2.0                  0.0            0.0   
...                ...           ...                  ...            ...   
3657              52.0           2.0                  0.0            0.0   
3658              18.0           2.0                  0.0            0.0   
3659              26.0           4.0                  0.0            0.0   
3660              13.0           3.0                  0.0            0.0   
3661              18.0           2.0                  0.0            0.0   

      url_num_query_para  url_ip_present  ...  html_num_tags('iframe')  \
0                    0.0             0.0  ...                      0.0   
1                    0.0             0.0  ...                      0.0   
2                    0.0             0.0  ...                      1.0   
3                    0.0             0.0  ...                      0.0   
4                    0.0             0.0  ...                      0.0   
...                  ...             ...  ...                      ...   
3657                 0.0             0.0  ...                      0.0   
3658                 0.0             0.0  ...                      1.0   
3659                 0.0             0.0  ...                      0.0   
3660                 0.0             0.0  ...                      0.0   
3661                 0.0             0.0  ...                      0.0   

      html_num_tags('script')  html_num_tags('embed')  \
0                         7.0                     0.0   
1                        18.0                     0.0   
2                        33.0                     0.0   
3                        15.0                     0.0   
4                        10.0                     0.0   
...                       ...                     ...   
3657                      0.0                     0.0   
3658                     14.0                     0.0   
3659                     13.0                     0.0   
3660                      0.0                     0.0   
3661                      3.0                     0.0   

      html_num_tags('object')  html_num_tags('div')  html_num_tags('head')  \
0                         0.0                   0.0                    1.0   
1                         0.0                  20.0                    1.0   
2                         0.0                 101.0                    1.0   
3                         0.0                 151.0                    1.0   
4                         0.0                 332.0                    1.0   
...                       ...                   ...                    ...   
3657                      0.0                  11.0                    1.0   
3658                      0.0                 212.0                    1.0   


In [ ]:
X_test

url_len  url_num_hyphens_dom  url_path_len  url_domain_len  \
0          97                    0     80.000000            17.0   
1          37                    0     22.000000            15.0   
2          44                    0     18.000000            20.0   
3          40                    0     14.000000            26.0   
4          43                    2      7.500000            26.0   
...       ...                  ...           ...             ...   
2436       63                    0      5.666667            17.0   
2437       36                    0      1.000000            35.0   
2438       45                    1     23.000000            22.0   
2439       24                    0     10.000000            14.0   
2440       33                    2     10.000000            22.0   

      url_hostname_len  url_num_dots  url_num_underscores  url_query_len  \
0            17.000000             4                    0              0   
1            15.000000             3                    1              0   
2            20.000000             3                    3              0   
3            26.000000             2                    0              0   
4            26.000000             2                    0              0   
...                ...           ...                  ...            ...   
2436         37.500000             4                    2              0   
2437         35.000000             2                    0              0   
2438         30.666667             2                    0              0   
2439         26.333333             3                    0              0   
2440         22.000000             2                    0              0   

      url_num_query_para  url_ip_present  ...  url_port  \
0                      0               0  ...         0   
1                      0               0  ...         0   
2                      0               0  ...         0   
3                      0               0  ...         0   
4                      0               0  ...         0   
...                  ...             ...  ...       ...   
2436                   0               0  ...         0   
2437                   0               0  ...         0   
2438                   0               0  ...         0   
2439                   0               1  ...         0   
2440                   0               0  ...         0   

      html_num_tags('iframe')  html_num_tags('script')  \
0                           0                     5.00   
1                           1                     5.50   
2                           0                     6.00   
3                           0                     4.75   
4                           0                     3.50   
...                       ...                      ...   
2436                        1                    18.00   
2437                        0                    27.00   
2438                        0                     8.00   
2439                        0                     3.00   
2440                        3                    36.00   

      html_num_tags('embed')  html_num_tags('object')  html_num_tags('div')  \
0                          0                        0                    12   
1                          0                        0                   158   
2                          3                        3                    34   
3                          0                        0                    29   
4                          0                        0                    41   
...                      ...                      ...                   ...   
2436                       0                        0                    79   
2437                       0                        0                    57   
2438                       0                        0                   199   
2439                       0                        0                    90   
2

In [ ]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 14.1 MB/s eta 0:00:00


In [ ]:
!pip install pycaret

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 481.8/481.8 kB 19.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 26.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.0/150.0 kB 20.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 6.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 78.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 883.2 kB/s eta 0:00:00


In [ ]:
!pip install boruta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 kB 3.5 MB/s eta 0:00:00


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy

# X, y 데이터 분리
X = X_train.iloc[:,:-1]
y = X_train['label']

# 랜덤 포레스트 모델 생성
rf = RandomForestClassifier(n_estimators=200, n_jobs=-1, class_weight='balanced', max_depth=100)

# Boruta 알고리즘 수행
boruta = BorutaPy(estimator=rf, n_estimators='auto', max_iter=100, verbose=2, random_state=42)
boruta.fit(X.values, y.values)

# 선택된 feature 확인
selected_features = X.columns[boruta.support_]
print(selected_features)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	21
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	21
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	21
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	21
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	21
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	21
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	21
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	9 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	10 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	11 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	12 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	13 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	14 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	15 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
Iteration: 	16 / 100
Confirmed: 	10
Tentative: 	4
Rejected: 	7
I

In [ ]:
len(selected_features)

12

In [ ]:
selected_features = ['url_len', 'url_num_hyphens_dom', 'url_path_len', 'url_domain_len',
       'url_hostname_len', 'url_num_dots', 'url_query_len', 'url_entropy',
       "html_num_tags('script')", "html_num_tags('div')",
       "html_num_tags('form')", "html_num_tags('a')"]

selected_features.append('label')
X_train = X_train[selected_features]

In [ ]:
x = X_train.iloc[:,:-1]
y = X_train['label']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

In [ ]:
y_test.shape

(916,)

In [ ]:
from pycaret.classification import *
clf = setup(data=X_train, target=y_train, use_gpu=True)

In [ ]:
models()

Name  \
ID                                          
lr                    Logistic Regression   
knn                K Neighbors Classifier   
nb                            Naive Bayes   
dt               Decision Tree Classifier   
svm                   SVM - Linear Kernel   
rbfsvm                SVM - Radial Kernel   
gpc           Gaussian Process Classifier   
mlp                        MLP Classifier   
ridge                    Ridge Classifier   
rf               Random Forest Classifier   
qda       Quadratic Discriminant Analysis   
ada                  Ada Boost Classifier   
gbc          Gradient Boosting Classifier   
lda          Linear Discriminant Analysis   
et                 Extra Trees Classifier   
xgboost         Extreme Gradient Boosting   
lightgbm  Light Gradient Boosting Machine   
catboost              CatBoost Classifier   
dummy                    Dummy Classifier   

                                                  Reference  Turbo  
ID                                                                  
lr        sklearn.linear_model._logistic.LogisticRegression   True  
knn       sklearn.neighbors._classification.KNeighborsCl...   True  
nb                           sklearn.naive_bayes.GaussianNB   True  
dt             sklearn.tree._classes.DecisionTreeClassifier   True  
svm       sklearn.linear_model._stochastic_gradient.SGDC...   True  
rbfsvm                             sklearn.svm._classes.SVC  False  
gpc       sklearn.gaussian_process._gpc.GaussianProcessC...  False  
mlp       sklearn.neural_network._multilayer_perceptron....  False  
ridge           sklearn.linear_model._ridge.RidgeClassifier   True  
rf          sklearn.ensemble._forest.RandomForestClassifier   True  
qda       sklearn.discriminant_analysis.QuadraticDiscrim...   True  
ada       sklearn.ensemble._weight_boosting.AdaBoostClas...   True  
gbc         sklearn.ensemble._gb.GradientBoostingClassifier   True  
lda       sklearn.discriminant_analysis.LinearDiscrimina...   True  
et            sklearn.ensemble._forest.ExtraTreesClassifier   True  
xgboost                       xgboost.sklearn.XGBClassifier   True  
lightgbm                    lightgbm.sklearn.LGBMClassifier   True  
catboost                   catboost.core.CatBoostClassifier   True  
dummy                         sklearn.dummy.DummyClassifier   True

In [ ]:
best_model = compare_models(n_select=8, include=['lr','knn','nb','svm','rf','xgboost','lightgbm','catboost'])

Processing:   0%|          | 0/44 [00:00<?, ?it/s]

In [ ]:
best_model

[XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=None, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               n_estimators=100, n_jobs=-1, num_parallel_tree=None,
               objective='binary:logistic', predictor=None, ...),
 LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
                importance_type='split', learning_rate=0.1, max_depth=-1,
                min_child_samples=20, min_child_weight=0.001, min_split

In [ ]:
tuned_best_model = tune_model(best_model[0])

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


In [ ]:
tuned_best_model1 = tune_model(best_model[1])

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [ ]:
tuned_best_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)

In [ ]:
tuned_best_model1.fit(X_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=3980, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
y_pred = tuned_best_model.predict(X_test)

from sklearn.metrics import *
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[443  21]
 [ 16 436]]
              precision    recall  f1-score   support

           0       0.97      0.95      0.96       464
           1       0.95      0.96      0.96       452

    accuracy                           0.96       916
   macro avg       0.96      0.96      0.96       916
weighted avg       0.96      0.96      0.96       916



In [ ]:
y_pred1 = tuned_best_model1.predict(X_test)

from sklearn.metrics import *
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

[[449  15]
 [ 19 433]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       464
           1       0.97      0.96      0.96       452

    accuracy                           0.96       916
   macro avg       0.96      0.96      0.96       916
weighted avg       0.96      0.96      0.96       916



In [ ]:
a = np.array([[0.491, 0.016],
              [0.021, 0.472]])

a

array([[0.491, 0.016],
       [0.021, 0.472]])

In [ ]:
a/916

array([[0.49017467, 0.01637555],
       [0.02074236, 0.47270742]])

In [12]:
(0.016*5600000) + (0.021*1000000000)

21089600.0

In [13]:
21089600.0 / 0.472

44681355.93220339

In [19]:
-14000000000 + (x*0.472 - 21089600.0) = 0

150400.0

In [21]:
(-14000000000+21089600)/0.472

-29616335593.22034